"""Regenerate the .mplstyle files in src/plotastro/styles/ from one template.

All journal styles share a single visual language; only the header, default
figure size and (for Nature Astronomy) the font block differ. Edit the
template or the JOURNALS dict below, then run:

    python tools/generate_styles.py
"""

from pathlib import Path

OUTDIR = Path(__file__).resolve().parents[1] / "src" / "plotastro" / "styles"

SERIF_FONTS = """font.family      : serif
font.serif       : Times New Roman, Times, Nimbus Roman, STIXGeneral, DejaVu Serif
font.size        : 9
mathtext.fontset : stix          # Times-compatible maths without LaTeX

# Full LaTeX text rendering (needs a working LaTeX installation).
# Uncomment below, or call plotastro.set_style("{key}", usetex=True).
#text.usetex         : True
#text.latex.preamble : \\usepackage{{newtxtext}}\\usepackage{{newtxmath}}"""

SANS_FONTS = """font.family      : sans-serif
font.sans-serif  : Arial, Helvetica, Nimbus Sans, DejaVu Sans
font.size        : 7             # Nature asks for 5-7 pt final lettering
mathtext.fontset : dejavusans    # sans-serif maths without LaTeX

# Full LaTeX text rendering (needs a working LaTeX installation).
# Uncomment below, or call plotastro.set_style("{key}", usetex=True).
#text.usetex         : True
#text.latex.preamble : \\usepackage{{helvet}}\\usepackage{{sansmath}}\\sansmath\\renewcommand{{\\familydefault}}{{\\sfdefault}}"""

JOURNALS = {
    "mnras": dict(
        title="Monthly Notices of the Royal Astronomical Society",
        widths=["one column : 240.00 pt = 3.32 in",
                "full width : 504.00 pt = 6.97 in",
                "(from the mnras LaTeX class)"],
        figsize="3.3209, 2.0524", fonts=SERIF_FONTS,
    ),
    "rasti": dict(
        title="RAS Techniques and Instruments (RASTI)",
        widths=["one column : 240.00 pt = 3.32 in",
                "full width : 504.00 pt = 6.97 in",
                "(RASTI uses the MNRAS-family LaTeX class)"],
        figsize="3.3209, 2.0524", fonts=SERIF_FONTS,
    ),
    "aanda": dict(
        title="Astronomy & Astrophysics (A&A)",
        widths=["one column : 250.38 pt = 3.46 in (88 mm)",
                "full width : 512.15 pt = 7.09 in (180 mm)",
                "(from the A&A author guide: 88 mm / 170-180 mm)"],
        figsize="3.4646, 2.1412", fonts=SERIF_FONTS,
    ),
    "apj": dict(
        title="The Astrophysical Journal (ApJ / ApJL, AASTeX v6.3+)",
        widths=["one column : 242.27 pt = 3.35 in",
                "full width : 513.12 pt = 7.10 in",
                "(from the aastex631 two-column class)"],
        figsize="3.3522, 2.0718", fonts=SERIF_FONTS,
    ),
    "oja": dict(
        title="The Open Journal of Astrophysics",
        widths=["one column : ~245.27 pt = 3.39 in",
                "full width : ~508.00 pt = 7.03 in",
                "(OJA's two-column template is emulateapj-like; measure",
                "\\the\\columnwidth in your own build for exact numbers)"],
        figsize="3.3937, 2.0975", fonts=SERIF_FONTS,
    ),
    "prd": dict(
        title="Physical Review D (REVTeX 4.2 two-column)",
        widths=["one column : 246.00 pt = 3.40 in",
                "full width : 510.00 pt = 7.06 in",
                "(from the revtex4-2 class; PRL uses the same layout)"],
        figsize="3.4039, 2.1037", fonts=SERIF_FONTS,
    ),
    "jcap": dict(
        title="Journal of Cosmology and Astroparticle Physics (JCAP)",
        widths=["single column layout: text width ~455 pt = 6.30 in (~16 cm)",
                "(approximate; measure \\the\\textwidth in your own build)"],
        figsize="6.2992, 3.8932", fonts=SERIF_FONTS,
    ),
    "natastro": dict(
        title="Nature Astronomy",
        widths=["one column : 253.23 pt = 3.50 in (89 mm)",
                "full width : 520.68 pt = 7.20 in (183 mm)",
                "(Nature-family figure guide; note the SANS-SERIF fonts",
                "and smaller lettering Nature requires)"],
        figsize="3.5039, 2.1656", fonts=SANS_FONTS,
    ),
}

TEMPLATE = """\
# =====================================================================
#  {key}.mplstyle — {title}
#
#  Figure widths:
{width_lines}
#  The default figsize below is one column wide with a golden-ratio
#  height. For other sizes use plotastro.figsize() / plotastro.subplots().
#
#  Colours: colour-blind-friendly cycle — see the README for details.
#  Generated by tools/generate_styles.py — edit that, not this file.
#
#  Usage:   import plotastro; plotastro.set_style("{key}")
#     or:   import plotastro; plt.style.use("{key}")
# =====================================================================

## ---- Lines & markers ------------------------------------------------
lines.linewidth       : 1.2
lines.markersize      : 4
lines.markeredgewidth : 0.8
errorbar.capsize      : 2
patch.linewidth       : 0.8

## ---- Fonts ----------------------------------------------------------
{fonts}

## ---- Axes -----------------------------------------------------------
axes.linewidth             : 0.6
axes.labelsize             : medium
axes.titlesize             : medium
axes.labelpad              : 3
axes.axisbelow             : True    # grid behind the data
axes.formatter.use_mathtext: True
axes.xmargin               : 0.03
axes.ymargin               : 0.05

# Colour-blind-friendly colour cycle (see README, "The colour palette")
axes.prop_cycle : cycler('color', ['377eb8', 'ff7f00', '4daf4a', 'f781bf', 'a65628', '984ea3', '999999', 'e41a1c', 'dede00', 'a2c8ec', 'ffbc79', 'ababab'])

## ---- Grid (subtle; set axes.grid: False to disable) -----------------
axes.grid      : True
grid.linewidth : 0.4
grid.alpha     : 0.25

## ---- Ticks: all four sides, pointing in, with minors ----------------
xtick.direction     : in
xtick.top           : True
xtick.bottom        : True
xtick.minor.visible : True
xtick.major.size    : 3.5
xtick.minor.size    : 2
xtick.major.width   : 0.6
xtick.minor.width   : 0.4
xtick.labelsize     : small      # ~1 pt below the base font size

ytick.direction     : in
ytick.left          : True
ytick.right         : True
ytick.minor.visible : True
ytick.major.size    : 3.5
ytick.minor.size    : 2
ytick.major.width   : 0.6
ytick.minor.width   : 0.4
ytick.labelsize     : small

## ---- Legend ---------------------------------------------------------
legend.fontsize       : small
legend.title_fontsize : small
legend.frameon        : False
legend.handlelength   : 1.8
legend.handletextpad  : 0.5
legend.labelspacing   : 0.3
legend.columnspacing  : 1.2
legend.borderaxespad  : 0.4

## ---- Figure ---------------------------------------------------------
figure.figsize                : {figsize}   # one column, golden ratio
figure.dpi                    : 150              # on-screen / notebook display
figure.titlesize              : medium
figure.constrained_layout.use : True             # no cut-off labels

## ---- Images ---------------------------------------------------------
image.cmap : viridis
#image.origin : lower    # uncomment for the astro image convention

## ---- Saving ---------------------------------------------------------
savefig.format     : pdf      # journals prefer vector formats
savefig.dpi        : 450      # comfortably above journal raster minimums
savefig.bbox       : tight
savefig.pad_inches : 0.02
pdf.fonttype       : 42       # embed TrueType fonts (no Type-3)
ps.fonttype        : 42
"""


def main():
    OUTDIR.mkdir(parents=True, exist_ok=True)
    for key, cfg in JOURNALS.items():
        width_lines = "\n".join(f"#      {line}" for line in cfg["widths"])
        text = TEMPLATE.format(key=key, title=cfg["title"],
                               width_lines=width_lines,
                               figsize=cfg["figsize"],
                               fonts=cfg["fonts"].format(key=key))
        (OUTDIR / f"{key}.mplstyle").write_text(text)
        print(f"wrote {OUTDIR / (key + '.mplstyle')}")


if __name__ == "__main__":
    main()
