"""Regenerate the .mplstyle files in src/plotastro/styles/ from templates.

All journal styles share a single visual language (TEMPLATE); only the
header, default figure size and (for Nature Astronomy) the font block
differ. The one exception is "euclid", which reproduces the look of the
Euclid Consortium's niceplots and therefore has its own EUCLID_TEMPLATE.
Edit the templates or the JOURNALS dict below, then run:

    python tools/generate_styles.py
"""

from pathlib import Path

OUTDIR = Path(__file__).resolve().parents[1] / "src" / "plotastro" / "styles"

SERIF_FONTS = """font.family      : serif
font.serif       : Times New Roman, Times, Nimbus Roman, STIXGeneral, DejaVu Serif
font.size        : 9
mathtext.fontset : stix          # Times-compatible maths without LaTeX

# Full LaTeX text rendering (needs a working LaTeX installation).
# Uncomment below, or call plotastro.set_style("{key}", usetex=True).
#text.usetex         : True
#text.latex.preamble : \\usepackage{{newtxtext}}\\usepackage{{newtxmath}}"""

SANS_FONTS = """font.family      : sans-serif
font.sans-serif  : Arial, Helvetica, Nimbus Sans, DejaVu Sans
font.size        : 7             # Nature asks for 5-7 pt final lettering
mathtext.fontset : dejavusans    # sans-serif maths without LaTeX

# Full LaTeX text rendering (needs a working LaTeX installation).
# Uncomment below, or call plotastro.set_style("{key}", usetex=True).
#text.usetex         : True
#text.latex.preamble : \\usepackage{{helvet}}\\usepackage{{sansmath}}\\sansmath\\renewcommand{{\\familydefault}}{{\\sfdefault}}"""

JOURNALS = {
    "mnras": dict(
        title="Monthly Notices of the Royal Astronomical Society",
        widths=["one column : 240.00 pt = 3.32 in",
                "full width : 504.00 pt = 6.97 in",
                "(from the mnras LaTeX class)"],
        figsize="3.3209, 2.0524", fonts=SERIF_FONTS,
    ),
    "rasti": dict(
        title="RAS Techniques and Instruments (RASTI)",
        widths=["one column : 240.00 pt = 3.32 in",
                "full width : 504.00 pt = 6.97 in",
                "(RASTI uses the MNRAS-family LaTeX class)"],
        figsize="3.3209, 2.0524", fonts=SERIF_FONTS,
    ),
    "aanda": dict(
        title="Astronomy & Astrophysics (A&A)",
        widths=["one column : 250.38 pt = 3.46 in (88 mm)",
                "full width : 512.15 pt = 7.09 in (180 mm)",
                "(from the A&A author guide: 88 mm / 170-180 mm)"],
        figsize="3.4646, 2.1412", fonts=SERIF_FONTS,
    ),
    "apj": dict(
        title="The Astrophysical Journal (ApJ / ApJL, AASTeX v6.3+)",
        widths=["one column : 242.27 pt = 3.35 in",
                "full width : 513.12 pt = 7.10 in",
                "(from the aastex631 two-column class)"],
        figsize="3.3522, 2.0718", fonts=SERIF_FONTS,
    ),
    "oja": dict(
        title="The Open Journal of Astrophysics",
        widths=["one column : ~245.27 pt = 3.39 in",
                "full width : ~508.00 pt = 7.03 in",
                "(OJA's two-column template is emulateapj-like; measure",
                "\\the\\columnwidth in your own build for exact numbers)"],
        figsize="3.3937, 2.0975", fonts=SERIF_FONTS,
    ),
    "prd": dict(
        title="Physical Review D (REVTeX 4.2 two-column)",
        widths=["one column : 246.00 pt = 3.40 in",
                "full width : 510.00 pt = 7.06 in",
                "(from the revtex4-2 class; PRL uses the same layout)"],
        figsize="3.4039, 2.1037", fonts=SERIF_FONTS,
    ),
    "jcap": dict(
        title="Journal of Cosmology and Astroparticle Physics (JCAP)",
        widths=["single column layout: text width ~455 pt = 6.30 in (~16 cm)",
                "(approximate; measure \\the\\textwidth in your own build)"],
        figsize="6.2992, 3.8932", fonts=SERIF_FONTS,
    ),
    "natastro": dict(
        title="Nature Astronomy",
        widths=["one column : 253.23 pt = 3.50 in (89 mm)",
                "full width : 520.68 pt = 7.20 in (183 mm)",
                "(Nature-family figure guide; note the SANS-SERIF fonts",
                "and smaller lettering Nature requires)"],
        figsize="3.5039, 2.1656", fonts=SANS_FONTS,
    ),
    "euclid": dict(
        title="Euclid Consortium papers (A&A), in the look of niceplots",
        widths=["drawn 4.00 in = 289.08 pt wide and scaled by LaTeX into",
                "the 88 mm A&A column; two columns: 8.00 in = 578.16 pt",
                "(niceplots' convention, see the note below)"],
        figsize="4.0, 3.0", fonts=None, template="euclid",
    ),
}

TEMPLATE = """\
# =====================================================================
#  {key}.mplstyle — {title}
#
#  Figure widths:
{width_lines}
#  The default figsize below is one column wide with a golden-ratio
#  height. For other sizes use plotastro.figsize() / plotastro.subplots().
#
#  Colours: colour-blind-friendly cycle — see the README for details.
#  Generated by tools/generate_styles.py — edit that, not this file.
#
#  Usage:   import plotastro; plotastro.set_style("{key}")
#     or:   import plotastro; plt.style.use("{key}")
# =====================================================================

## ---- Lines & markers ------------------------------------------------
lines.linewidth       : 1.2
lines.markersize      : 4
lines.markeredgewidth : 0.8
errorbar.capsize      : 2
patch.linewidth       : 0.8

## ---- Fonts ----------------------------------------------------------
{fonts}

## ---- Axes -----------------------------------------------------------
axes.linewidth             : 0.6
axes.labelsize             : medium
axes.titlesize             : medium
axes.labelpad              : 3
axes.axisbelow             : True    # grid behind the data
axes.formatter.use_mathtext: True
axes.xmargin               : 0.03
axes.ymargin               : 0.05

# Colour-blind-friendly colour cycle (see README, "The colour palette")
axes.prop_cycle : cycler('color', ['377eb8', 'ff7f00', '4daf4a', 'f781bf', 'a65628', '984ea3', '999999', 'e41a1c', 'dede00', 'a2c8ec', 'ffbc79', 'ababab'])

## ---- Grid (subtle; set axes.grid: False to disable) -----------------
axes.grid      : True
grid.linewidth : 0.4
grid.alpha     : 0.25

## ---- Ticks: all four sides, pointing in, with minors ----------------
xtick.direction     : in
xtick.top           : True
xtick.bottom        : True
xtick.minor.visible : True
xtick.major.size    : 3.5
xtick.minor.size    : 2
xtick.major.width   : 0.6
xtick.minor.width   : 0.4
xtick.labelsize     : small      # ~1 pt below the base font size

ytick.direction     : in
ytick.left          : True
ytick.right         : True
ytick.minor.visible : True
ytick.major.size    : 3.5
ytick.minor.size    : 2
ytick.major.width   : 0.6
ytick.minor.width   : 0.4
ytick.labelsize     : small

## ---- Legend ---------------------------------------------------------
legend.fontsize       : small
legend.title_fontsize : small
legend.frameon        : False
legend.handlelength   : 1.8
legend.handletextpad  : 0.5
legend.labelspacing   : 0.3
legend.columnspacing  : 1.2
legend.borderaxespad  : 0.4

## ---- Figure ---------------------------------------------------------
figure.figsize                : {figsize}   # one column, golden ratio
figure.dpi                    : 150              # on-screen / notebook display
figure.titlesize              : medium
figure.constrained_layout.use : True             # no cut-off labels

## ---- Images ---------------------------------------------------------
image.cmap : viridis
#image.origin : lower    # uncomment for the astro image convention

## ---- Saving ---------------------------------------------------------
savefig.format     : pdf      # journals prefer vector formats
savefig.dpi        : 450      # comfortably above journal raster minimums
savefig.bbox       : tight
savefig.pad_inches : 0.02
pdf.fonttype       : 42       # embed TrueType fonts (no Type-3)
ps.fonttype        : 42
"""


# Petroff (2021) 8-colour palette, niceplots' default cycle ("categorical1").
# Keep in sync with plotastro.PETROFF8.
EUCLID_CYCLE = ["1845fb", "ff5e02", "c91f16", "c849a9",
                "adad7d", "86c8dd", "578dff", "656364"]

# The Euclid style is a different visual language, so it has its own
# template. The values are those of niceplots' euclid_stylesheet v2,
# re-expressed here; parameters niceplots leaves at matplotlib's defaults
# are written out so that switching from another plotastro style is clean.
EUCLID_TEMPLATE = """\
# =====================================================================
#  {key}.mplstyle — {title}
#
#  The look of this style is adapted from "niceplots", the Euclid
#  Consortium Editorial Board's matplotlib style for Euclid papers
#  (euclid_stylesheet v2, set up by Lukas Hergt with tweaks by Laila
#  Linke; GPL-3.0; https://gitlab.euclid-sgs.uk/ECEB/niceplots,
#  Euclid-internal). Its settings are re-expressed in plotastro's own
#  template; no file or code from niceplots is included. Parameters that
#  niceplots leaves at matplotlib's defaults are written out here so that
#  switching from another plotastro style is clean. Two plotastro
#  additions that do not change the look: constrained layout (niceplots'
#  finalizePlot() calls tight_layout() instead) and Type-42 font
#  embedding for submission-safe PDFs.
#
#  Figure widths:
{width_lines}
#  niceplots' convention is to draw every figure 4.0 x 3.0 in with 10 pt
#  lettering and let LaTeX scale it into the 88 mm A&A column, where it
#  prints at ~8.7 pt; a two-column figure is drawn twice as large.
#  plotastro.figsize() / subplots() follow that convention for this
#  style. For a figure at its exact printed size instead, keep the style
#  and size it for A&A: plotastro.subplots(journal="aanda").
#
#  Colours: Petroff (2021) 8-colour palette (plotastro.PETROFF8),
#  niceplots' default. Its other schemes: plotastro.euclid_colors() or
#  plotastro.set_style("{key}", palette="categorical3").
#  Generated by tools/generate_styles.py — edit that, not this file.
#
#  Usage:   import plotastro; plotastro.set_style("{key}")
#     or:   import plotastro; plt.style.use("{key}")
# =====================================================================

## ---- Lines & markers ------------------------------------------------
lines.linewidth       : 1.0
lines.markersize      : 5.0
lines.markeredgewidth : 1.0      # matplotlib default
errorbar.capsize      : 0        # matplotlib default
patch.linewidth       : 1.0      # matplotlib default

## ---- Fonts: sans-serif text, Computer Modern maths ------------------
font.family      : sans-serif
font.sans-serif  : DejaVu Sans, Bitstream Vera Sans, Computer Modern Sans Serif, Lucida Grande, Verdana, Geneva, Lucid, Arial, Helvetica, Avant Garde, sans-serif
font.size        : 10
mathtext.fontset : cm            # Computer Modern, like LaTeX's default maths

# niceplots turns LaTeX on whenever a `latex` binary is found; text is then
# set in Computer Modern Sans (matplotlib adds \\sffamily itself, so no
# preamble is needed). Same thing: plotastro.set_style("{key}", usetex=True).
#text.usetex : True

## ---- Axes -----------------------------------------------------------
axes.linewidth             : 0.6
axes.facecolor             : white
axes.labelsize             : medium
axes.titlesize             : large
axes.labelpad              : 4.0     # matplotlib default
axes.axisbelow             : line    # matplotlib default
axes.formatter.use_mathtext: False   # matplotlib default
axes.xmargin               : 0       # data spans the full x range
axes.ymargin               : 0.05    # matplotlib default

# Petroff (2021) 8-colour palette — plotastro.PETROFF8
axes.prop_cycle : cycler('color', [{palette}])

## ---- Grid: off, as in niceplots (set_style(grid=True) for a subtle one)
axes.grid      : False
grid.linewidth : 0.4
grid.alpha     : 0.25

## ---- Ticks: all four sides, pointing in, no minors ------------------
xtick.direction     : in
xtick.top           : True
xtick.bottom        : True
xtick.minor.visible : False
xtick.major.size    : 2.5
xtick.minor.size    : 1.5
xtick.major.width   : 0.6
xtick.minor.width   : 0.4
xtick.major.pad     : 5.0
xtick.labelsize     : medium

ytick.direction     : in
ytick.left          : True
ytick.right         : True
ytick.minor.visible : False
ytick.major.size    : 2.5
ytick.minor.size    : 1.5
ytick.major.width   : 0.6
ytick.minor.width   : 0.4
ytick.major.pad     : 5.0
ytick.labelsize     : medium

## ---- Legend: matplotlib's defaults (framed) -------------------------
legend.fontsize       : medium
legend.title_fontsize : None
legend.frameon        : True
legend.handlelength   : 2.0
legend.handletextpad  : 0.8
legend.labelspacing   : 0.5
legend.columnspacing  : 2.0
legend.borderaxespad  : 0.5

## ---- Figure ---------------------------------------------------------
figure.figsize                : {figsize}   # niceplots' 4:3 default (see header)
figure.dpi                    : 200         # on-screen / notebook display
figure.titlesize              : large       # matplotlib default
figure.constrained_layout.use : True        # plotastro addition (see header)

## ---- Images ---------------------------------------------------------
image.cmap : viridis      # matplotlib default
#image.origin : lower    # uncomment for the astro image convention

## ---- Saving ---------------------------------------------------------
savefig.format     : pdf
savefig.dpi        : 300      # for raster formats
savefig.bbox       : tight
savefig.pad_inches : 0.02
pdf.fonttype       : 42       # plotastro addition: embed TrueType fonts (no Type-3)
ps.fonttype        : 42
"""

TEMPLATES = {"default": TEMPLATE, "euclid": EUCLID_TEMPLATE}


def main():
    OUTDIR.mkdir(parents=True, exist_ok=True)
    palette = ", ".join(f"'{c}'" for c in EUCLID_CYCLE)
    for key, cfg in JOURNALS.items():
        width_lines = "\n".join(f"#      {line}" for line in cfg["widths"])
        template = TEMPLATES[cfg.get("template", "default")]
        fonts = cfg["fonts"].format(key=key) if cfg.get("fonts") else ""
        text = template.format(key=key, title=cfg["title"],
                               width_lines=width_lines,
                               figsize=cfg["figsize"], fonts=fonts,
                               palette=palette)
        (OUTDIR / f"{key}.mplstyle").write_text(text)
        print(f"wrote {OUTDIR / (key + '.mplstyle')}")


if __name__ == "__main__":
    main()
